services:
  - type: worker
    name: icholding-dingtalk-bot
    env: node
    plan: starter
    buildCommand: "yarn install"
    startCommand: "node bot.js"
    autoDeploy: true
    envVars:
      - key: DINGTALK_API_KEY
        sync: false
      - key: DINGTALK_SECRET
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: GITHUB_REPO_NAME
        value: "ICholding.cloud"
